### ISSUE TITLE
Cannot work

### ISSUE THREAD

**Issue by DutchPete** [ivan-lednev/obsidian-persistent-links#1]
The `main.js` file is missing.

**Comment by ivan-lednev** [comment]
Hello, @DutchPete!

Did you expect to find it in the source files?

If you want to try out the plugin before it's added to the community plugins list, the best option is the BRAT plugin: https://github.com/TfTHacker/obsidian42-brat.

You can also grab main.js & manifest.json from the release page:  https://github.com/ivan-lednev/obsidian-persistent-links/releases.

**Comment by DutchPete** [comment]
“If you want to try out the plugin before it's added to the community plugins list, the best option is the BRAT plugin”

My apologies, I had forgotten about that one. Yep, the plug-in works fine now.
